package wkbp.battleships.model;

import java.util.List;

/**
 * Represents given pool of ships as a unit to be placed on board
 * Consists of List of ships {@link Ship}
 *
 * @author Wiktor Rup
 */
public class Fleet {

    private List<Ship> shipList;

    /**
     * @param shipList generated by FleetFactory {@link FleetFactory}
     */
    public Fleet(List<Ship> shipList) {
        this.shipList = shipList;
    }

    public List<Ship> getShipList() {
        return shipList;
    }
}
